
include ../../make-util/discover-toolset.mk
include ../../make-util/discover-task-models.mk

SEQ_ENABLED:=1
WOMP_ENABLED:=$(OPENMP_ENABLED)

SOURCES:=pi.cc

LINKATOMIC=$(LIBATOMIC)

include ../common.mk
