
include ../../make-util/discover-toolset.mk
include ../../make-util/discover-task-models.mk

# derived from BOTS (include its original version)
WOMP_ENABLED=1

# source files
SOURCES=knapsack.cc

include ../common.mk
