
include ../../make-util/discover-toolset.mk
include ../../make-util/discover-task-models.mk

# derived from BOTS (include its original version)
WOMP_ENABLED:=$(OPENMP_ENABLED)

# source files
SOURCES:=knapsack.cc

include ../common.mk
