
include ../../make-util/discover-toolset.mk
include ../../make-util/discover-task-models.mk

# derived from BOTS (include its original version)
WOMP_ENABLED:=1
SEQ_ENABLED:=1

SOURCES=uts.cc brg_sha1.cc

include ../common.mk
