# derived from BOTS (include its original version)
BOTS_ORIGINAL=1

# problems with a task's max stack size
#   see also alignment
#~ QTHREADS_ENABLED=0

# source files
SOURCES=floorplan.cc

include ../common.mk
