
include ../../make-util/discover-toolset.mk
include ../../make-util/discover-task-models.mk

CXXVERSION:=-std=c++14

SEQ_ENABLED:=1
WOMP_ENABLED:=1
QTHREADS_ENABLED:=0
TBB_ENABLED:=0

SOURCES:=msort.cc

include ../common.mk
